fix: 改用 secrets.GITHUB_TOKEN 來認證看看
Traceback:
- name: Push changes to target repository
Push to branch main
/home/runner/work/_actions/ad-m/github-push-action/master/start.sh: line 18: Missing input 'github_token: ${{ secrets.GITHUB_TOKEN }}'.: bad substitution
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:30:21)
    at ChildProcess.emit (node:events:524:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1
}